In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_digits
digits = load_digits()

In [3]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size = 0.3)

#### Logistic Regression

In [47]:
lr  = LogisticRegression(solver = 'liblinear',multi_class = 'ovr')
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9481481481481482



#### SVM

In [63]:
svm = SVC(gamma = 'auto')
svm.fit(X_train,y_train)



SVC(gamma='auto')

In [64]:
svm.score(X_test,y_test)

0.3592592592592593

In [49]:
svm = SVC(gamma = 'scale')
svm.fit(X_train,y_train)
svm.score(X_test,y_test)


0.9925925925925926




#### Random Forest

In [66]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9740740740740741

## KFold cross validation

In [68]:
from sklearn.model_selection import KFold
kf = KFold(n_splits =3 )
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [69]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


###### Use KFold for our digits example 

In [70]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [79]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    
    scores_logistic.append(get_score(LogisticRegression(solver = 'liblinear',multi_class = 'ovr'),X_train,X_test,y_train,y_test))

    scores_svm.append(get_score(SVC(gamma = 'auto'), X_train,X_test,y_train,y_test ))
    scores_rf.append(get_score(RandomForestClassifier(), X_train,X_test,y_train,y_test ))

In [82]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [83]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [84]:
scores_rf

[0.9398998330550918, 0.9549248747913188, 0.9248747913188647]

## cross_val_score function

In [85]:
from sklearn.model_selection import cross_val_score

In [89]:
cross_val_score(LogisticRegression(solver = 'liblinear',multi_class = 'ovr'),digits.data,digits.target,cv =3)

array([0.89482471, 0.95325543, 0.90984975])

In [90]:
cross_val_score(SVC(gamma = 'auto'),digits.data,digits.target,cv =3)

array([0.38063439, 0.41068447, 0.51252087])

In [91]:
cross_val_score(RandomForestClassifier(n_estimators = 40),digits.data,digits.target,cv = 3)

array([0.92654424, 0.93656093, 0.91986644])






## parameter tunning using kfold cross validation

In [92]:

scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8837150837988826

In [98]:

scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9326660459342022

In [99]:

scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9343358162631905

In [100]:

scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9426815642458101





## Exercise

In [108]:
from sklearn.datasets import load_iris
import pandas as pd

In [109]:
iris = load_iris()

In [110]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [111]:
df = pd.DataFrame(iris.data,columns = iris.feature_names)

In [115]:
X = df
y = iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [125]:
from sklearn.tree import DecisionTreeClassifier

In [117]:
from sklearn.model_selection import cross_val_score

In [140]:
l_scores  = cross_val_score(LogisticRegression(solver = 'liblinear'),X,y,cv = 5)
np.average(l_scores)

0.9600000000000002

In [141]:
s_scores = cross_val_score(SVC(gamma = 'auto'),X,y,cv = 5)
np.average(s_scores)

0.9800000000000001

In [142]:
D_scores = cross_val_score(DecisionTreeClassifier(),X,y,cv = 5)
np.average(D_scores)

0.9600000000000002

In [143]:
R_scores = cross_val_score(RandomForestClassifier(n_estimators= 40),X,y,cv =5)
np.average(R_scores)

0.9666666666666668

#### Best score so far is from SVM : 0.9800000000000001