In [1]:
import pandas as pd


In [2]:
df = pd.read_csv('titanic.csv')
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis = 1,inplace = True)

In [4]:
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [5]:
inputs = df.drop(['Survived'],axis =1)
inputs

Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [6]:
target = df.Survived
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [7]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [8]:
inputs = pd.concat([inputs,dummies],axis = 1)
inputs.head()

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [9]:
inputs.drop(['Sex','male'],axis = 1,inplace = True)

In [10]:
inputs.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [11]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [12]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [13]:
inputs.Age= inputs.Age.fillna(inputs.Age.mean())
inputs.Age[:10]

0    22.000000
1    38.000000
2    26.000000
3    35.000000
4    35.000000
5    29.699118
6    54.000000
7     2.000000
8    27.000000
9    14.000000
Name: Age, dtype: float64

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(inputs,target,test_size = 0.3)


In [15]:
from sklearn.naive_bayes  import GaussianNB
model = GaussianNB()

In [16]:
model.fit(X_train,y_train)

GaussianNB()

In [17]:
model.score(X_test,y_test)

0.7611940298507462

In [18]:
X_test[:10]

Pclass        Age     Fare  female
725       3  20.000000   8.6625       0
369       1  24.000000  69.3000       1
446       2  13.000000  19.5000       1
858       3  24.000000  19.2583       1
15        2  55.000000  16.0000       1
420       3  29.699118   7.8958       0
870       3  26.000000   7.8958       0
681       1  27.000000  76.7292       0
381       3   1.000000  15.7417       1
809       1  33.000000  53.1000       1

In [19]:
y_test[:10]

725    0
369    1
446    1
858    1
15     1
420    0
870    0
681    1
381    1
809    1
Name: Survived, dtype: int64

In [20]:
model.predict(X_test[:10])

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 1], dtype=int64)

In [21]:
model.predict_proba(X_test[:10])

array([[0.96566123, 0.03433877],
       [0.02271932, 0.97728068],
       [0.20012058, 0.79987942],
       [0.41886174, 0.58113826],
       [0.24288242, 0.75711758],
       [0.96912921, 0.03087079],
       [0.96802936, 0.03197064],
       [0.41421399, 0.58578601],
       [0.31495899, 0.68504101],
       [0.0439386 , 0.9560614 ]])

#### Calculate the score using cross validation

In [22]:
import numpy as np

In [23]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(GaussianNB(),X_train,y_train,cv = 6)
score

array([0.78846154, 0.73076923, 0.75      , 0.80769231, 0.79807692,
       0.82524272])

In [24]:
np.average(score)

0.783373786407767

# Part2

In [53]:
df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [54]:
 df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [55]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [56]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size = 0.2
                                                )

In [57]:
X_train.values

array(["Dont worry. I guess he's busy.",
       'PRIVATE! Your 2003 Account Statement for shows 800 un-redeemed S. I. M. points. Call 08719899230 Identifier Code: 41685 Expires 07/11/04',
       'It took Mr owl 3 licks', ...,
       'Lol alright i was thinkin that too haha',
       'I cant keep talking to people if am not sure i can pay them if they agree to price. So pls tell me what you want to really buy and how much you are willing to pay',
       'life alle mone,eppolum oru pole allalo'], dtype=object)

In [58]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [59]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [60]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [61]:
X_test_count = v.transform(X_test)
model.score(X_test_count,y_test)

0.9856502242152466

#### By creating pipeline

In [63]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [64]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [65]:
clf.score(X_test,y_test)

0.9856502242152466

In [66]:
clf.predict(emails)

array([0, 1], dtype=int64)

# Exercise

In [67]:
from sklearn.datasets import load_wine
wine = load_wine()

In [68]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [71]:
df = pd.DataFrame(wine.data,columns = wine.feature_names)

In [72]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [73]:
df['target'] = wine.target

In [74]:
df['target']

0      0
1      0
2      0
3      0
4      0
      ..
173    2
174    2
175    2
176    2
177    2
Name: target, Length: 178, dtype: int32

In [75]:
df['target_names'] = df['target'].apply(lambda x : wine.target_names[x])

In [76]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target target_names  
0                          3.92   1065.0       0      class_0  
1                          3.40   1050.0       0      class_0  
2                          3.17   1185.0       0      class_0  
3                          3.45   1480.0       0      class_0  
4                          2.93    735.0       0      class_0

In [78]:
df.groupby('target').describe()

alcohol                                                             \
         count       mean       std    min     25%     50%     75%    max   
target                                                                      
0         59.0  13.744746  0.462125  12.85  13.400  13.750  14.100  14.83   
1         71.0  12.278732  0.537964  11.03  11.915  12.290  12.515  13.86   
2         48.0  13.153750  0.530241  12.20  12.805  13.165  13.505  14.34   

       malic_acid            ... od280/od315_of_diluted_wines       proline  \
            count      mean  ...                          75%   max   count   
target                       ...                                              
0            59.0  2.010678  ...                         3.42  4.00    59.0   
1            71.0  1.932676  ...                         3.16  3.69    71.0   
2            48.0  3.333750  ...                         1.82  2.47    48.0   

                                                                       
               mean         std    min    25%     50%     75%     max  
target                                                                 
0       1115.711864  221.520767  680.0  987.5  1095.0  1280.0  1680.0  
1        519.507042  157.211220  278.0  406.5   495.0   625.0   985.0  
2        629.895833  115.097043  415.0  545.0   627.5   695.0   880.0  

[3 rows x 104 columns]

In [79]:
inputs = df.drop(['target','target_names'],axis =1)

In [80]:
inputs

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [82]:
df.columns[df.isna().any()].tolist()

[]

In [83]:
target = df.target

In [84]:
target

0      0
1      0
2      0
3      0
4      0
      ..
173    2
174    2
175    2
176    2
177    2
Name: target, Length: 178, dtype: int32

In [97]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(inputs,target,test_size = 0.3,random_state = 100)


In [98]:
from sklearn.naive_bayes  import GaussianNB
model1 = GaussianNB()

In [99]:
model1.fit(X_train,y_train)

GaussianNB()

In [100]:
model1.score(X_test,y_test)

1.0

In [101]:
from sklearn.naive_bayes import MultinomialNB
model2 = MultinomialNB()

In [102]:
model2.fit(X_train,y_train)

MultinomialNB()

In [103]:
model2.score(X_test,y_test)

0.7777777777777778