In [42]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [43]:
df = pd.read_csv("homeprices.csv")
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [44]:
df = df.drop('town' , axis =1)

In [45]:
df

area   price
0   2600  550000
1   3000  565000
2   3200  610000
3   3600  680000
4   4000  725000
5   2600  585000
6   2800  615000
7   3300  650000
8   3600  710000
9   2600  575000
10  2900  600000
11  3100  620000
12  3600  695000

In [46]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [47]:
model.coef_

array([118.29495955])

In [48]:
model.intercept_


257056.62725575588

In [49]:
model.predict([[5000]])

array([848531.42501556])

## pickle

In [50]:
import pickle 

In [51]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [52]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [53]:
mp.coef_

array([118.29495955])

In [54]:
mp.intercept_

257056.62725575588

In [55]:
mp.predict([[5000]])

array([848531.42501556])

## joblib

In [56]:
 import joblib

In [57]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [58]:
mj = joblib.load('model_joblib')

In [59]:
mj.coef_

array([118.29495955])

In [61]:
mj.predict([[5000]])

array([848531.42501556])